# Generated by Django 3.0 on 2025-02-04 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expenses',
        ),
    ]
