# Generated by Django 3.0 on 2025-02-04 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_expenses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='Budget',
            new_name='BUDGET',
        ),
    ]
