# Generated by Django 3.0 on 2025-02-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20250204_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='Discription',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
