# Generated by Django 3.0 on 2025-02-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_expenses_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='Date',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
