# Generated by Django 3.0 on 2025-02-09 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_tax_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestions',
            name='USER',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.User'),
        ),
    ]
