# Generated by Django 3.0 on 2025-02-09 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_suggestions_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestions',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User'),
        ),
    ]
