# Generated by Django 3.0 on 2025-02-09 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_expertrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expertrequest',
            old_name='Expert',
            new_name='EXPERT',
        ),
    ]
