# Generated by Django 3.0 on 2025-02-10 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20250209_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='BUDGET',
        ),
        migrations.AddField(
            model_name='review',
            name='Expert',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Expert'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='App_Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Review', models.CharField(max_length=100)),
                ('Rating', models.CharField(max_length=100)),
                ('Date', models.CharField(max_length=100)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User')),
            ],
        ),
    ]
