# Generated by Django 3.0 on 2025-02-10 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20250210_1701'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='ExpertReview',
        ),
    ]
