# Generated by Django 3.0 on 2025-02-10 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20250210_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expertreview',
            old_name='Expert',
            new_name='EXPERT',
        ),
    ]
