# Generated by Django 3.0 on 2025-02-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20250210_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertrequest',
            name='message',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
