# Generated by Django 3.0 on 2025-02-15 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_expertrequest_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expertrequest',
            old_name='message',
            new_name='Enquiries',
        ),
    ]
