# Generated by Django 3.0 on 2025-02-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20250226_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='Type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
