# Generated by Django 3.0 on 2025-03-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_expenses_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='Date',
            field=models.DateField(),
        ),
    ]
