# Generated by Django 3.0 on 2025-03-06 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20250301_1607'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expenses',
        ),
    ]
